server:
  port: 8083
  tomcat:
    uri-encoding: UTF-8
    max-threads: 600
  max-http-header-size: 102400
  context-path: /utils-pro/

spring:
  application:
    name: nacos-consumer-service

provider:
  demo:
    application:
      name: nacos-provider-service
    parse.url: /provider/parse